// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjBksYqLXh6jIm8KwYDTCUyTef7eqU6R0',
    appId: '1:789377331142:web:ff73ad8a4d481548748cc7',
    messagingSenderId: '789377331142',
    projectId: 'newsify-b84f0',
    authDomain: 'newsify-b84f0.firebaseapp.com',
    storageBucket: 'newsify-b84f0.appspot.com',
    measurementId: 'G-C90NESJSRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjyzsAD69mv3NbMEXe5IadV8C8FHMox9w',
    appId: '1:789377331142:android:f14ac383253a7850748cc7',
    messagingSenderId: '789377331142',
    projectId: 'newsify-b84f0',
    storageBucket: 'newsify-b84f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-St-b1E6ePKB8_9ptB93rkOyFgpQo_c',
    appId: '1:789377331142:ios:dc4affeac862a6e7748cc7',
    messagingSenderId: '789377331142',
    projectId: 'newsify-b84f0',
    storageBucket: 'newsify-b84f0.appspot.com',
    iosBundleId: 'com.example.newsify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI-St-b1E6ePKB8_9ptB93rkOyFgpQo_c',
    appId: '1:789377331142:ios:dc4affeac862a6e7748cc7',
    messagingSenderId: '789377331142',
    projectId: 'newsify-b84f0',
    storageBucket: 'newsify-b84f0.appspot.com',
    iosBundleId: 'com.example.newsify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjBksYqLXh6jIm8KwYDTCUyTef7eqU6R0',
    appId: '1:789377331142:web:52646fecc7617ba2748cc7',
    messagingSenderId: '789377331142',
    projectId: 'newsify-b84f0',
    authDomain: 'newsify-b84f0.firebaseapp.com',
    storageBucket: 'newsify-b84f0.appspot.com',
    measurementId: 'G-VCPJ0PZJKC',
  );
}
